### ISSUE TITLE
Error when using docker-compose

### ISSUE THREAD

**Issue by Emanuel-Bjurhager** [inoda/ontrack#85]
Steps to replicate error:
sudo git clone https://github.com/inoda/ontrack.git

cd ontrack

sudo docker-compose up -d

create user as specified in readme

then go to the webpage and login. Firefox console shows this error:

Uncaught Error: Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot find module 'babel-plugin-macros'
Require stack:
- /ontrack/babel.config.js
- /ontrack/node_modules/@babel/core/lib/config/files/module-types.js
- /ontrack/node_modules/@babel/core/lib/config/files/configuration.js
- /ontrack/node_modules/@babel/core/lib/config/files/index.js
- /ontrack/node_modules/@babel/core/lib/index.js
- /ontrack/node_modules/babel-loader/lib/index.js
- /ontrack/node_modules/loader-runner/lib/loadLoader.js
- /ontrack/node_modules/loader-runner/lib/LoaderRunner.js
- /ontrack/node_modules/webpack/lib/NormalModule.js
- /ontrack/node_modules/webpack/lib/index.js
- /ontrack/node_modules/webpack-cli/lib/webpack-cli.js
- /ontrack/node_modules/webpack-cli/lib/bootstrap.js
- /ontrack/node_modules/webpack-cli/bin/cli.js
- /ontrack/node_modules/webpack/bin/webpack.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at module.exports (/ontrack/babel.config.js:47:7)
    at startHiding - secret - don't use this - v1 (/ontrack/node_modules/@babel/core/lib/errors/rewrite-stack-trace.js:59:12)
    at readConfigJS (/ontrack/node_modules/@babel/core/lib/config/files/configuration.js:228:66)
    at readConfigJS.next (<anonymous>)
    at Function.<anonymous> (/ontrack/node_modules/@babel/core/lib/gensync-utils/async.js:27:3)
    at Generator.next (<anonymous>)
    jsx dashboard.js:9
    Webpack 5
    
   I have tried this 2 times and got the same issue both times

**Comment by hugginsio** [comment]
I was able to reproduce this issue with the latest commit, `[d7409a4](https://github.com/inoda/ontrack/commit/d7409a49b46f815d9d6a7773bdb63324b571e067)`. Applying the change specified in #83 and rebuilding the container image resolved the issue for me.
